sudo: required
services:
  - docker

before_install:
  - docker build -t mahosind95/docker-web -f Dockerfile.dev .

script: 
  - docker run -e CI=true mahosind95/docker-web npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-web"
  env: "Dockerweb-env"
  bukcet_name: "elasticbeanstalk-us-east-1-447851550607" 
  bucket_path: "docker-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY